# Generated by Django 5.2 on 2026-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(max_length=20)),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='open', max_length=20)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('assigned_to', models.CharField(default='Unassigned', max_length=100)),
                ('created_by', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('assigned_to', models.CharField(default='Unassigned', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('parent_issue_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
